### ISSUE TITLE
Unable to listen on 'localhost'

### ISSUE THREAD

**Issue by Danatobob** [jchristn/WatsonWebsocket#21]
I'm using 2.0.2 version from NuGet.
The docs say 

> When you configure WatsonWebsocket to listen on 127.0.0.1 or localhost

But I can't listen on "localhost" as that produces an exception on IPAddress.Parse call. I can't listen on "127.0.0.1" either as I get "Access denied" exception and I don't want to run any netsh commands to workaround that.

**Comment by jchristn** [comment]
Hi @Danatobob thanks for letting me know. I will look at it this morning!

**Comment by jchristn** [comment]
Hi @Danatobob thanks for filing this issue.  I fixed this and made some other long-overdue (breaking) changes that will make the library better.  1) instead of Func-based callbacks it now uses Event, and 2) IpPort is now a property instead of a method on ClientMetadata.  Everything else should work as expected.  Please re-open if that is not the case!

NuGet v2.1.0: https://www.nuget.org/packages/WatsonWebsocket/2.1.0
Commit: https://github.com/jchristn/WatsonWebsocket/commit/a1f7dd63bcc1cd2888fc3c4ae8a991aa67b1af83

**Comment by Danatobob** [comment]
Oh, thanks, that was fast. I was actually wondering why Func is used for callbacks when studying the class ;).

**Comment by Danatobob** [comment]
>  Please re-open if that is not the case!

version 2.1.1 from NuGet
for ClientConnected event I get this

```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
WatsonWebsocket.ClientConnectedEventArgs.HttpRequest.get returned null.
```

I can't reopen this issue though. I'll create new one i guess

**Comment by jchristn** [comment]
Looking into it momentarily

**Comment by jchristn** [comment]
Oops, just saw your other issue, closing this one
