### ISSUE TITLE
ClientDisonnectedEventArgs  misspell

### ISSUE THREAD

**Issue by caozero** [jchristn/WatsonWebsocket#23]
/// <summary>
  /// Event arguments for when a client disconnects from the server.
  /// </summary>
  public class ClientDisonnectedEventArgs : EventArgs
  {
    internal ClientDisonnectedEventArgs(string ipPort)
    {
      this.IpPort = ipPort;
    }

    /// <summary>The IP:port of the client.</summary>
    public string IpPort { get; }
  }

ClientDisconnectedEventArgs

**Comment by jchristn** [comment]
Hi @caozero did you have an issue to report?

**Comment by Danatobob** [comment]
He means there is a typo: 
 ClientDisonnectedEventArgs -> ClientDis`c`onnectedEventArgs

**Comment by jchristn** [comment]
Oh!  Thank you!  I will fix that this morning. Thank you for catching!

**Comment by jchristn** [comment]
@caozero thank you for catching this and @Danatobob thank you for clarifying what the issue was.  I guess I was a little too close to the fire on that one.  Really appreciate you both making this library better!

NuGet v2.1.3: https://www.nuget.org/packages/WatsonWebsocket/2.1.3
Commit: https://github.com/jchristn/WatsonWebsocket/commit/5dd22957dc580b5a752bebf81dec20535c4303a6
