### ISSUE TITLE
Closing handshake

### ISSUE THREAD

**Issue by MartyIX** [jchristn/WatsonWebsocket#39]
Hi Joel,

I'm dealing with graceful close of the WebSocket connection where I use your `WatsonWsServer` and .NET's [ClientWebSocket](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netcore-3.1) class and I kind of think that `WatsonWsServer` does [not](https://github.com/jchristn/WatsonWebsocket/blob/master/WatsonWebsocket/WatsonWsServer.cs#L505) respond to a close from my client with a close frame as indicated here https://tools.ietf.org/html/rfc6455#section-1.4 

Could you please confirm or explain how it should/does work?

Cheers!

**Comment by jchristn** [comment]
Hi @MartyIX great question and it definitely is not.  I took too many liberties around the check for whether or not the connection was being closed or had already been closed.  I'll put this on the list and get something integrated that is in better alignment with expectations laid out in the RFC.  Thanks for letting me know!

**Comment by jchristn** [comment]
Sorry for the delay @MartyIX I'm looking at this now

**Comment by jchristn** [comment]
Hi @MartyIX I found a rather useful article on the proper way to close a websocket here: https://mcguirev10.com/2019/08/17/how-to-close-websocket-correctly.html

The interesting thing I found in my testing is that, even when I explicitly call ```ClientWebSocket.CloseOutputAsync``` from the client (which the author indicates is the proper way to manage your way through the closing states from a client-initiated point of view), the server ```WebSocket``` doesn't seem to ever be exposed to this message.

For instance, in the client code:
```
protected virtual void Dispose(bool disposing)
{
    if (disposing)
    {
        _TokenSource.Cancel();

        if (_ClientWs != null)
        {
            try
            {
                // see https://mcguirev10.com/2019/08/17/how-to-close-websocket-correctly.html
                _ClientWs.CloseOutputAsync(WebSocketCloseStatus.NormalClosure, "", new CancellationTokenSource().Token).Wait();
                _ClientWs.Dispose();
            }
            catch (Exception)
            {

            }
        }

        Logger?.Invoke("[WatsonWsClient] dispose complete");
    }
}
```

and in the server's data receiver (specifically in MessageReadAsync:
```
WebSocketReceiveResult result = await md.Ws.ReceiveAsync(seg, md.TokenSource.Token);
Console.WriteLine(result.MessageType.ToString());
```

I never see a ```WebSocketMessageType.Close``` appear.

So I decided to test a little farther by doing a ```Console.WriteLine``` of the exception that is thrown (which causes the server-side data receiver to terminate) and it generates a very generic ```WebSocketException```:
```
[WatsonWsServer.DataReceiver ::1:52384] websocket disconnected
System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<ReadAsyncCore>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WatsonWebsocket.WatsonWsServer.<MessageReadAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WatsonWebsocket.WatsonWsServer.<DataReceiver>d__47.MoveNext()
Client disconnected: ::1:52384
[WatsonWsServer.DataReceiver ::1:52384] disconnected
```

I wanted to make sure the client was actually calling the ```CloseOutputAsync``` method, so I changed the client's ```Dispose``` to:
```
try
{ 
    Console.WriteLine("Calling close output async");
    _ClientWs.CloseOutputAsync(WebSocketCloseStatus.NormalClosure, "", new CancellationTokenSource().Token).Wait();
    Console.WriteLine("Disposing websocket");
    _ClientWs.Dispose();
}
catch (Exception e)
{
    Console.WriteLine(e.ToString());
}
```

(don't laugh at the use of ```Console.WriteLine```, it's just easy/fast)

And on the client, I see:
```
System.AggregateException: One or more errors occurred. ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake.
```

Then I started looking into the ```WebSocketReceiveResult.CloseStatus``` property, and even that is never getting set.

I then, server-side again, checked the ```WebSocket.State``` while receiving messages, and while I see a state of ```Open``` reflected on the ```WebSocket``` (viewing from the server) any time I received a text/binary message from a client, I never see any other state such as ```CloseSent```, ```Closed```, etc.

I'm kind of at a loss here, because if I instruct the client to send a close via ```CloseOutputAsync``` yet I can't find a way on the server to even receive a message indicating that a close is happening, I can't respond accordingly.  The author mentions there is an issue resolved in 3.0 where *the client will never properly close the websocket*, and the library is targeted toward 2.0.  

I think my next course of action is to attempt a retarget to 3.0 to see if this can be worked out.

Sorry for the long-winded response, and I'm looking forward to your feedback/input.

**Comment by jchristn** [comment]
Testing with .NET Core 3.1.

On the server's message reader, I added:
```
WebSocketReceiveResult result = await md.Ws.ReceiveAsync(seg, md.TokenSource.Token);
Console.WriteLine("Websocket state : " + md.Ws.State);
Console.WriteLine("Close status    : " + result.CloseStatus);
Console.WriteLine("Message type    : " + result.MessageType);
```

When I send a text message from the client, I see this on the server:
```
Websocket state : Open
Close status    :
Message type    : Text
Text from ::1:52665: asdf
```

When I call ```Dispose``` from the client (which uses ```CloseAsync```), I see nothing.  When I change client's ```Dispose``` to use ```CloseOutputAsync```, I still see nothing on the server-side.

**Comment by jchristn** [comment]
@MartyIX I think I have at least the start of something worked out.  More updates to come.  Sorry for the email spam.

**Comment by jchristn** [comment]
Just published v2.2.0.5 to NuGet: https://www.nuget.org/packages/WatsonWebsocket/2.2.0.5
Commit here: https://github.com/jchristn/WatsonWebsocket/commit/799c6151306cef614435d9d1d97a3ca64e838377

Please let me know if this resolves the issue for you!  Tested it on both .NET Core 2.0 and 3.1, seems to be working now.  If all is well please close.  Cheers, Joel

**Comment by MartyIX** [comment]
It looks good, thank you!

**Comment by MartyIX** [comment]
Thank you for working on this!
