### ISSUE TITLE
Rate Throttling Behavior

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonWebsocket#47]
So if I send several dozen msgs as fast as possible to Chromium, a group of them (say a dozen) go out instantly back to back...
Then only a single message is sent at a time on an interval of approximately one second... for about 2 or 3 messages.
Then another dozen or so are sent rapid-fire together.  Then more individual slow ones.

What is going on here?

I looked through the Watson code for "limit" "rate" and "throttl" but didn't find anything.

**Comment by jchristn** [comment]
Hi @pha3z I would suspect it's because the thread pool doesn't pre-allocate enough.  If you continue the behavior in a loop for some time, does the condition improve?

I suspect what we're encountering is related to what's found here: https://stackoverflow.com/questions/6000834/threadpool-max-threads

We could modify the code to preset the thread pool min/max values and see if that makes a difference.

This response from that link was particularly insightful:
![image](https://user-images.githubusercontent.com/1421081/99029199-be805b00-2526-11eb-8c4d-742c3f3d6ca9.png)

**Comment by pha3z** [comment]
You were right on the money! All I had to do to fix the problem was set the min thread count.

> If you continue the behavior in a loop for some time, does the condition improve?
Sort of.  It clearly increases the thread pool size to about a dozen or so... but it seems to bounce around.  It doesn't increase enough for the awaiting work.  I'm not surprised, because there's no way the algorithm could know your intent.  It doesn't know whether the backlogged tasks should remain backlogged or if you really want more threads to spin up.

`            int workerThreads;
            int ioThreads;

            ThreadPool.GetMinThreads(out workerThreads, out ioThreads);
            _log.Debug($"Default workerThreads: {workerThreads}. Default ioThreads: {ioThreads}");

            ThreadPool.SetMinThreads(100, 100);
            ThreadPool.GetMinThreads(out workerThreads, out ioThreads);
            _log.Debug($"Default workerThreads: {workerThreads}. Default ioThreads: {ioThreads}");
`

Outputs:
`Nov 13 07:56:24 [DBG] Default workerThreads: 4. Default ioThreads: 4
Nov 13 07:56:24 [DBG] Default workerThreads: 100. Default ioThreads: 100
Nov 13 07:56:24 [INF] Press q to shut down application`

After changing the min thread count, I can spin up 100 Tasks to send messages, and they all run immediately.

Now that being said, after you pointed out to me what's going on, I realized the way I've architected this is all wrong.
I was using Task.Run() to execute synchronous blocking code for my custom Received handlers.  I changed them to async Task and used Task.Delay() for my internal simulation of long-running tasks instead of Thread.Sleep() (which I hadn't mentioned I was doing).

Using this design, the default thread pool size is plenty for the Task Scheduler to handles all Tasks in the blink of an eye.

It does take me back to my other Issue where I asked about making server.MessageReceived() an async method instead of void.  Because I'm not the first person who would struggle a bit to recognize that he/she needs to spin up his own Tasks and make sure to invoke asynchronous methods.  If server.MessageReceived() was already an async Task, then the "async zombie virus effect" would have naturally caused me to reach toward making my internal handlers also async Task instead of void (simply following a pattern).

This is the type of thing that either requires more documentation (ugh, more time writing!) or better handlebars so the developer naturally does what's best.

Is there any scenario or reason why server.MessageReceived() would function better as a void method instead of an async Task?

**Comment by pha3z** [comment]
I just read that you answered my question on the other issue:

> We could modify the data receiver to do a Task unawaited = Task.Run(() => MessageReceived?.Invoke(this, msg). Under normal circumstances that would work fine, but could create a condition (under heavy load) where messages may be delivered out of order (since we don't control how tasks are scheduled/executed). Thoughts?

I'll respond on that issue.

**Comment by jchristn** [comment]
Hi @pha3z re: your question "Is there any scenario or reason why server.MessageReceived() would function better as a void method instead of an async Task?" the main benefit I've found (and the reason why I've adopted it so heavily in the code I write) is simply better resource utilization (efficiency).  I found it difficult to maintain reasonable levels of CPU utilization with any kind of server that has a connection acceptance loop.  To make matters worse, the ThreadPool model espoused as a best practice (at the time) was from a syntactic perspective ugly at best.  The async/await model is IMO cleaner aesthetically, easier to understand, but yes has the side effect of sprawling through everything eventually.

To your question, there should **not** be any effect whether you use ```void``` or ```async Task``` in your event handler, aside from the need to do async within your own code.  From a performance perspective, I wouldn't anticipate any difference, because AFAIK, the ```async``` modifier in a method signature really does nothing other than allow you to use ```await``` within the method.  

I did per your recommendation change the server and client to fire off unawaited tasks instead of invoking the event handlers synchronously.  I think the problem of out-of-order messages would really only be a problem under heavy load, and in those cases, a lot of the issue can be remedied by manually adjusting the thread pool.

I'll close this one out, but please feel free to re-open if needed!  Also happy to continue the conversation here.  Thanks again for your continued help in making the library better!
