### ISSUE TITLE
The Client no heartbeat function

### ISSUE THREAD

**Issue by manyhelp** [jchristn/WatsonWebsocket#79]
The Client no heartbeat function

**Comment by jchristn** [comment]
Hi @manyhelp can you describe what issue you're encountering?

**Comment by manyhelp** [comment]
no problem.  I think client need heartbeat function.

**Comment by jchristn** [comment]
I intentionally did not build this kind of function into any of my libraries because it creates restrictions on the way you use the library.  For instance, if I send a JSON message containing a heartbeat, every message has to be examined before being passed to your code.  Thus I prefer this functionality be in your code.

**Comment by manyhelp** [comment]
All right. thank you
