### ISSUE TITLE
Allocation-free version of Receive

### ISSUE THREAD

**Issue by joreg** [jchristn/WatsonWebsocket#94]
hey joel,

would you accept a breaking PR that makes the Receive for both client and server allocation-free?

example on the client:
https://github.com/jchristn/WatsonWebsocket/blob/6cf7731ab84084c5ed6cb43365fbe77f6d475443/WatsonWebsocket/WatsonWsClient.cs#L602

here the internal function is returning an ArraySegment of which currently two copies are made: first into a MemoryStream, then into the buffer (which is also currently allocated twice: L607 and L614). returning the ArraySegment directly therefore get rid of two allocations.

i'm afraid this would be a minor breaking change, since the MessageReceivedEventArgs will need to have ArraySegment of byte instead of byte[] for data. would you still be accepting this? (if so, i'd PR the same for SuperSimpleTCP then which has the same issue)

**Comment by jchristn** [comment]
Hi @joreg I agree it's the right thing to do, because it aligns the input structures with the underlying implementation.  I would love a PR on these (happily on any library I manage) and will just increment the major version number (and of course add you to the README as a contributor!).  Cheers, Joel
